"""
Export utilities for MarketingOS
Handles Word, PDF, and formatted text exports
"""

from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from datetime import datetime
import os

def export_to_word(content, title="MarketingOS Content", filename=None):
    """
    Export content to a professional Word document
    
    Args:
        content (str): The content to export
        title (str): Document title
        filename (str): Optional custom filename
        
    Returns:
        str: Path to the created file
    """
    # Create document
    doc = Document()
    
    # Add title
    title_paragraph = doc.add_heading(title, 0)
    title_paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    # Add metadata
    meta = doc.add_paragraph()
    meta.add_run(f"Generated by MarketingOS v4.0\n").italic = True
    meta.add_run(f"Date: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}").italic = True
    meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    # Add separator
    doc.add_paragraph("_" * 60)
    
    # Add main content
    # Split by paragraphs and format
    paragraphs = content.split('\n\n')
    
    for para in paragraphs:
        if para.strip():
            # Check if it's a heading (starts with # or **)
            if para.strip().startswith('#'):
                # Remove # symbols and add as heading
                heading_text = para.strip().lstrip('#').strip()
                doc.add_heading(heading_text, level=1)
            elif para.strip().startswith('**') and para.strip().endswith('**'):
                # Bold heading
                heading_text = para.strip().strip('*').strip()
                doc.add_heading(heading_text, level=2)
            else:
                # Regular paragraph
                p = doc.add_paragraph(para.strip())
                p.alignment = WD_ALIGN_PARAGRAPH.LEFT
    
    # Add footer
    doc.add_paragraph("\n" + "_" * 60)
    footer = doc.add_paragraph()
    footer.add_run("\nPowered by MarketingOS v4.0 - AI Marketing Automation").italic = True
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    # Generate filename
    if not filename:
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        filename = f"MarketingOS_Export_{timestamp}.docx"
    
    # Ensure .docx extension
    if not filename.endswith('.docx'):
        filename += '.docx'
    
    # Save document
    doc.save(filename)
    
    return filename


def export_to_markdown(content, title="MarketingOS Content", filename=None):
    """
    Export content to Markdown file
    
    Args:
        content (str): The content to export
        title (str): Document title
        filename (str): Optional custom filename
        
    Returns:
        str: Path to the created file
    """
    # Generate filename
    if not filename:
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        filename = f"MarketingOS_Export_{timestamp}.md"
    
    # Ensure .md extension
    if not filename.endswith('.md'):
        filename += '.md'
    
    # Create markdown content
    markdown_content = f"""# {title}

*Generated by MarketingOS v4.0*  
*Date: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}*

---

{content}

---

*Powered by MarketingOS v4.0 - AI Marketing Automation*
"""
    
    # Write to file
    with open(filename, 'w', encoding='utf-8') as f:
        f.write(markdown_content)
    
    return filename


def export_to_text(content, title="MarketingOS Content", filename=None):
    """
    Export content to plain text file
    
    Args:
        content (str): The content to export
        title (str): Document title
        filename (str): Optional custom filename
        
    Returns:
        str: Path to the created file
    """
    # Generate filename
    if not filename:
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        filename = f"MarketingOS_Export_{timestamp}.txt"
    
    # Ensure .txt extension
    if not filename.endswith('.txt'):
        filename += '.txt'
    
    # Create text content
    text_content = f"""{title}
{'=' * len(title)}

Generated by MarketingOS v4.0
Date: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}

{'-' * 60}

{content}

{'-' * 60}

Powered by MarketingOS v4.0 - AI Marketing Automation
"""
    
    # Write to file
    with open(filename, 'w', encoding='utf-8') as f:
        f.write(text_content)
    
    return filename


def get_file_size(filename):
    """Get file size in human-readable format"""
    size_bytes = os.path.getsize(filename)
    
    if size_bytes < 1024:
        return f"{size_bytes} bytes"
    elif size_bytes < 1024 * 1024:
        return f"{size_bytes / 1024:.2f} KB"
    else:
        return f"{size_bytes / (1024 * 1024):.2f} MB"