"""
Report Generator — SwarmOps
Generates downloadable markdown marketing reports from audit data.
GET /api/audit/{id}/report returns a full consultant-quality report.
"""

import json
from datetime import datetime
from typing import Optional


class ReportGenerator:

    def generate_audit_report(self, audit_data: dict) -> str:
        """Generate a comprehensive marketing report as markdown."""

        brand = audit_data.get("brand", {})
        brand_name = brand.get("name", audit_data.get("url", "Website"))
        industry = brand.get("industry", "General Business")
        scores = audit_data.get("scores", {})
        grade = audit_data.get("grade", "N/A")
        overall_score = audit_data.get("overall_score", 0)
        sections = audit_data.get("sections", {})
        simulation = audit_data.get("improvement_simulation", {})
        actions = audit_data.get("priority_actions", [])
        exec_summary = audit_data.get("executive_summary", "No summary available.")
        audit_date = audit_data.get("audit_date", datetime.utcnow().isoformat())
        url = audit_data.get("url", "")

        def score_emoji(s):
            if s >= 80: return "🟢 Strong"
            if s >= 60: return "🟡 Needs Work"
            return "🔴 Critical"

        # --- Score table ---
        score_rows = "\n".join(
            f"| {k.upper()} | {v}/100 | {score_emoji(v)} |"
            for k, v in scores.items()
        )

        # --- Brand intelligence block ---
        brand_voice = brand.get("brand_voice", {})
        target_audience = brand.get("target_audience", {})
        value_prop = brand.get("value_proposition", {})

        if isinstance(brand_voice, dict):
            voice_str = f"Tone: {brand_voice.get('tone', 'N/A')}, Style: {brand_voice.get('writing_style', 'N/A')}, Formality: {brand_voice.get('formality_level', 'N/A')}/10"
        else:
            voice_str = str(brand_voice)

        if isinstance(target_audience, dict):
            audience_str = f"{target_audience.get('primary', 'N/A')} ({target_audience.get('company_size', 'N/A')})"
        else:
            audience_str = str(target_audience)

        if isinstance(value_prop, dict):
            vp_str = value_prop.get("primary", "N/A")
            differentiator = value_prop.get("unique_differentiator", "")
        else:
            vp_str = str(value_prop)
            differentiator = ""

        # --- Priority actions ---
        actions_md = ""
        for i, action in enumerate(actions[:10], 1):
            if isinstance(action, dict):
                act_text = action.get("action", str(action))
                section = action.get("section", "").upper()
                atype = action.get("type", "")
                tag = f"[{section}]" if section else ""
                win_tag = " ⚡ Quick Win" if atype == "quick_win" else ""
                actions_md += f"\n{i}. {tag}{win_tag} {act_text}"
            else:
                actions_md += f"\n{i}. {action}"

        # --- Improvement simulation ---
        sim_overall = simulation.get("overall", {})
        sim_sections = simulation.get("sections", {})

        sim_table_rows = "\n".join(
            f"| {k.upper()} | {v.get('current_score', 0)}/100 | {v.get('potential_score', 0)}/100 | {v.get('traffic_impact', 'N/A')} | {v.get('conversion_impact', 'N/A')} |"
            for k, v in sim_sections.items()
        )

        overall_sim = ""
        if sim_overall:
            overall_sim = f"""
| Metric | Current | Potential |
|--------|---------|-----------|
| Grade | {sim_overall.get('current_grade', grade)} | {sim_overall.get('potential_grade', 'N/A')} |
| Traffic | Baseline | {sim_overall.get('estimated_traffic_increase', 'N/A')} |
| Conversions | Baseline | {sim_overall.get('estimated_conversion_increase', 'N/A')} |
| Revenue | Current | {sim_overall.get('estimated_revenue_opportunity', 'N/A')} |

**Timeframe:** {sim_overall.get('timeframe', '3-6 months')}
"""

        report = f"""# Marketing Intelligence Report
## {brand_name} — {url}
**Generated by SwarmOps AI | {audit_date[:10] if audit_date else 'Today'}**

---

## Overall Grade: {grade} ({overall_score}/100)

---

## Executive Summary

{exec_summary}

---

## Score Breakdown

| Section | Score | Status |
|---------|-------|--------|
{score_rows}

---

## Brand Intelligence

| Attribute | Value |
|-----------|-------|
| **Brand** | {brand_name} |
| **Industry** | {industry} |
| **URL** | {url} |
| **Brand Voice** | {voice_str} |
| **Target Audience** | {audience_str} |
| **Value Proposition** | {vp_str} |
{f'| **Unique Differentiator** | {differentiator} |' if differentiator and differentiator != "Not detected" else ''}

---

## SEO Analysis

{self._format_section(sections.get('seo_audit', {}))}

---

## Content Strategy

{self._format_section(sections.get('content_audit', {}))}

---

## Conversion Optimization (CRO)

{self._format_section(sections.get('cro_audit', {}))}

---

## Messaging Analysis

{self._format_section(sections.get('messaging_audit', {}))}

---

## PPC Strategy

{self._format_section(sections.get('ppc_strategy', {}))}

---

## Competitive Landscape

{self._format_section(sections.get('competitive_landscape', {}))}

---

## Growth Opportunities

{self._format_section(sections.get('growth_opportunities', {}))}

---

## Top 10 Priority Actions
{actions_md}

---

## Improvement Simulation (3-6 Months)

### By Section

| Section | Current | Potential | Traffic Impact | Conversion Impact |
|---------|---------|-----------|----------------|-------------------|
{sim_table_rows}

### Overall Impact
{overall_sim}

---

## How to Use This Report

1. **Start with the highest-priority quick wins** (marked ⚡) — these are low-effort, high-impact
2. **Schedule the 3 lowest-scoring sections** for focused improvement sprints
3. **Revisit this audit in 90 days** to track progress and update scores
4. **Share section-specific findings** with relevant team members (SEO → content team, CRO → product/design)

---

*This report was generated by SwarmOps AI Marketing Intelligence.*
*11 specialized agents analyzed {url} across SEO, content, CRO, messaging, competitive positioning, PPC, and growth.*
*Scores are based on AI analysis of publicly available website signals and industry benchmarks.*
"""
        return report.strip()

    def _format_section(self, section_data: dict) -> str:
        """Format a section dict into readable markdown."""
        if not section_data:
            return "_Analysis not available._"
        if isinstance(section_data, str):
            return section_data
        if "error" in section_data:
            return f"_Analysis encountered an issue: {section_data['error']}_"

        output_parts = []

        # Score badge
        score = section_data.get("score")
        if score is not None:
            emoji = "🟢" if score >= 80 else "🟡" if score >= 60 else "🔴"
            output_parts.append(f"**Score: {score}/100 {emoji}**\n")

        # Sub-scores
        sub_scores = {k: v for k, v in section_data.items()
                      if k.endswith("_score") and k != "score" and isinstance(v, (int, float))}
        if sub_scores:
            sub_parts = " | ".join(f"{k.replace('_score','').upper()}: {v}" for k, v in sub_scores.items())
            output_parts.append(f"_{sub_parts}_\n")

        # Key lists
        key_order = [
            ("quick_wins", "⚡ Quick Wins"),
            ("friction_points", "Friction Points"),
            ("weaknesses", "Weaknesses"),
            ("content_gaps", "Content Gaps"),
            ("market_gaps", "Market Gaps"),
            ("competitive_strengths", "Competitive Strengths"),
            ("top_keyword_opportunities", "Top Keyword Opportunities"),
            ("top_content_ideas", "Top Content Ideas"),
            ("opportunities", "Growth Opportunities"),
            ("recommendations", "Recommendations"),
        ]

        for key, label in key_order:
            values = section_data.get(key, [])
            if values and isinstance(values, list):
                output_parts.append(f"**{label}:**")
                for item in values[:5]:
                    if isinstance(item, dict):
                        # Handle nested objects (e.g. competitors, keywords)
                        line = " | ".join(f"{k}: {v}" for k, v in item.items() if v and v != "Not detected")
                        output_parts.append(f"- {line}")
                    elif item and str(item) != "Not detected":
                        output_parts.append(f"- {item}")
                output_parts.append("")

        # Improved headlines / taglines
        for key, label in [("improved_headlines", "Improved Headlines"), ("improved_taglines", "Improved Taglines"), ("ad_headlines", "Ad Headlines")]:
            values = section_data.get(key, [])
            if values:
                output_parts.append(f"**{label}:**")
                for item in values[:3]:
                    output_parts.append(f'> "{item}"')
                output_parts.append("")

        # Budget guidance
        if "budget_guidance" in section_data:
            bg = section_data["budget_guidance"]
            if isinstance(bg, dict):
                output_parts.append(f"**Budget Guidance:** Min {bg.get('minimum_monthly','N/A')} | Recommended {bg.get('recommended_monthly','N/A')} | Expected ROAS {bg.get('expected_roas','N/A')}")
                output_parts.append("")

        # Estimated conversion lift
        if "estimated_conversion_lift" in section_data:
            output_parts.append(f"**Estimated Conversion Lift:** {section_data['estimated_conversion_lift']}")

        return "\n".join(output_parts) if output_parts else "_No findings available._"


# ---------------------------------------------------------------------------
# Singleton factory
# ---------------------------------------------------------------------------

_generator_instance: Optional[ReportGenerator] = None


def get_report_generator() -> ReportGenerator:
    global _generator_instance
    if _generator_instance is None:
        _generator_instance = ReportGenerator()
    return _generator_instance
