from typing import Dict, List, Optional
from pydantic import BaseModel

class RegistryEntry(BaseModel):
    signal_type: str
    category: str
    default_title: str
    default_description: str
    what_issue_means: str
    why_it_matters: str
    business_impact: str
    seo_aeo_impact: str
    default_impact_score: float  # 1.0 - 10.0
    default_effort_score: float  # 1.0 - 10.0
    default_urgency_score: float  # 1.0 - 10.0
    default_confidence_score: float  # 1.0 - 10.0
    business_relevance_score: float  # 1.0 - 10.0
    exact_fix: str
    implementation_example: str
    verification_method: str
    resolved_when: str
    evidence_safe_wording: str
    avoid_claims: List[str]
    recommended_specialists: List[str]


CANONICAL_REGISTRY: Dict[str, RegistryEntry] = {
    "missing_robots_txt": RegistryEntry(
        signal_type="opportunity_window",
        category="seo",
        default_title="No robots.txt file",
        default_description="A robots.txt file gives you control over how search engines crawl your site.",
        what_issue_means="The search engine crawlers did not find crawl instructions at the root of the site.",
        why_it_matters="A robots.txt file controls crawler access, not indexing. It guides search agents to crawl important pages and save resources.",
        business_impact="Maintains crawl efficiency and helps protect administrative or private directories from crawler overload.",
        seo_aeo_impact="Guides search bots to optimize crawl budget allocation across key marketing pages.",
        default_impact_score=3.0,
        default_effort_score=1.0,
        default_urgency_score=2.0,
        default_confidence_score=9.5,
        business_relevance_score=3.0,
        exact_fix="Create a text file named robots.txt and upload it to your website's root directory.",
        implementation_example="User-agent: *\nAllow: /\n\nSitemap: https://shravanpayyavula.me/sitemap.xml",
        verification_method="Visit /robots.txt and confirm a 200 HTTP status code.",
        resolved_when="The URL returns a 200 OK status code with valid robot directive content.",
        evidence_safe_wording="robots.txt controls crawler access, not indexing.",
        avoid_claims=["robots.txt controls indexing", "robots.txt prevents pages from appearing in search results"],
        recommended_specialists=["seo", "aeo", "cro"]
    ),
    "robots_txt_blocks_all": RegistryEntry(
        signal_type="risk_alert",
        category="risk",
        default_title="Robots.txt blocks search indexing",
        default_description="Your robots.txt file is currently instructing crawlers not to crawl any pages.",
        what_issue_means="The robots.txt file contains a Disallow directive blocking all search engines.",
        why_it_matters="When crawlers are blocked, they cannot read your site content, which halts organic indexing updates.",
        business_impact="Prevents your business from acquiring organic customers from Google, Perplexity, or Bing.",
        seo_aeo_impact="Blocks search crawlers and AI answer engine web scrapers from discovering or indexing content.",
        default_impact_score=10.0,
        default_effort_score=1.0,
        default_urgency_score=10.0,
        default_confidence_score=9.8,
        business_relevance_score=10.0,
        exact_fix="Update the robots.txt file to allow crawler access, specifically removing Disallow: /.",
        implementation_example="User-agent: *\nAllow: /",
        verification_method="Verify robots.txt has no 'Disallow: /' block and returns a 200 HTTP status code.",
        resolved_when="The robots.txt file content is updated to remove the wild disallow rule.",
        evidence_safe_wording="robots.txt blocks crawler access, preventing search engines from crawling the site.",
        avoid_claims=["robots.txt automatically deletes pages from index", "robots.txt resolves canonical errors"],
        recommended_specialists=["seo", "aeo", "cro"]
    ),
    "missing_sitemap": RegistryEntry(
        signal_type="opportunity_window",
        category="seo",
        default_title="Missing XML sitemap reference",
        default_description="Sitemaps help search engines discover and crawl all of your important pages.",
        what_issue_means="No sitemap reference was declared in the robots.txt file or found at standard sitemap locations.",
        why_it_matters="An XML sitemap helps crawlers discover and index new or deep pages, especially on sites with complex structures.",
        business_impact="Speeds up the discovery of new product launches and marketing campaigns by search engines.",
        seo_aeo_impact="Provides a structured index of your website urls directly to search engine bots.",
        default_impact_score=4.0,
        default_effort_score=2.0,
        default_urgency_score=3.0,
        default_confidence_score=9.0,
        business_relevance_score=4.0,
        exact_fix="Generate an XML sitemap and add a reference link inside your robots.txt file.",
        implementation_example="Sitemap: https://yourdomain.com/sitemap.xml",
        verification_method="Access the sitemap URL directly in a browser and check robots.txt for a Sitemap line.",
        resolved_when="A Sitemap URL is successfully parsed from robots.txt or found at /sitemap.xml.",
        evidence_safe_wording="XML sitemaps provide an explicit crawler roadmap for page discovery.",
        avoid_claims=["Sitemaps guarantee 100% indexing", "Sitemaps improve rankings directly by 20%"],
        recommended_specialists=["seo", "operations"]
    ),
    "missing_meta_description": RegistryEntry(
        signal_type="opportunity_window",
        category="seo",
        default_title="Missing meta description on key pages",
        default_description="A meta description summarizes a page's content for search snippets.",
        what_issue_means="The HTML header is missing a <meta name=\"description\"> tag.",
        why_it_matters="A clear meta description may improve snippet quality and click appeal when search engines choose to display it.",
        business_impact="Increases organic search listing click-through appeal, drawing more qualified prospects to your site.",
        seo_aeo_impact="Assists search engines in displaying helpful snippets in organic search listings.",
        default_impact_score=5.0,
        default_effort_score=2.0,
        default_urgency_score=4.0,
        default_confidence_score=9.5,
        business_relevance_score=5.0,
        exact_fix="Add a <meta name=\"description\" content=\"...\"> tag to the HTML head (150-160 characters).",
        implementation_example="<meta name=\"description\" content=\"SwarmOps coordinates specialized AI agents to automate your technical marketing audits and growth campaigns.\">",
        verification_method="Inspect the page HTML head for a meta description tag containing description content.",
        resolved_when="A meta description tag is present in the homepage HTML head.",
        evidence_safe_wording="A clear meta description may improve snippet quality and click appeal when search engines choose to display it.",
        avoid_claims=["Meta descriptions improve CTR by 30%", "Meta descriptions are a direct Google ranking factor"],
        recommended_specialists=["seo", "content", "cro"]
    ),
    "duplicate_meta_description": RegistryEntry(
        signal_type="opportunity_window",
        category="seo",
        default_title="Duplicate meta descriptions detected",
        default_description="Different pages share identical meta descriptions.",
        what_issue_means="Multiple pages contain the same meta description text in their HTML head.",
        why_it_matters="Duplicate descriptions prevent search engines from generating unique snippets for distinct pages.",
        business_impact="Blurs the distinction between different service offerings, reducing user click relevancy.",
        seo_aeo_impact="Confuses search engines regarding which page is most relevant to a specific search query.",
        default_impact_score=4.0,
        default_effort_score=3.0,
        default_urgency_score=3.0,
        default_confidence_score=8.5,
        business_relevance_score=4.0,
        exact_fix="Write unique meta descriptions tailored specifically to the unique value proposition of each page.",
        implementation_example="<meta name=\"description\" content=\"Unique description tailored specifically to this page's topics.\">",
        verification_method="Compare meta description text across audited pages to ensure they are unique.",
        resolved_when="All crawled pages have unique meta descriptions or duplicates are removed.",
        evidence_safe_wording="Unique meta descriptions help ensure each page has a tailored search snippet.",
        avoid_claims=["Duplicate meta descriptions trigger a Google penalty", "Duplicate descriptions stop page crawling"],
        recommended_specialists=["seo", "content"]
    ),
    "missing_title": RegistryEntry(
        signal_type="risk_alert",
        category="risk",
        default_title="Missing or empty <title> tag",
        default_description="Your homepage has no title tag. This is the single biggest on-page SEO factor.",
        what_issue_means="The HTML contains an empty, missing, or defaulted <title> tag.",
        why_it_matters="The title tag is critical for both search engines (to index the page topic) and users (tab headings).",
        business_impact="Crucial organic listings will fail to show or render as unnamed or broken links.",
        seo_aeo_impact="A missing title tag makes the page highly difficult for search engines to rank accurately.",
        default_impact_score=9.0,
        default_effort_score=1.0,
        default_urgency_score=9.0,
        default_confidence_score=9.9,
        business_relevance_score=9.0,
        exact_fix="Add a unique, descriptive <title> tag inside the HTML head (under 60 characters).",
        implementation_example="<title>SwarmOps | Multi-Agent AI Marketing & SEO Operations</title>",
        verification_method="Inspect the HTML source code for the presence of a non-empty <title> tag.",
        resolved_when="A valid, populated <title> tag is found in the page HTML head.",
        evidence_safe_wording="A descriptive title tag defines the page subject for search bots and browsers.",
        avoid_claims=["Title tags boost domain authority directly", "Title tags guarantee high search rankings"],
        recommended_specialists=["seo", "content", "cro"]
    ),
    "duplicate_title": RegistryEntry(
        signal_type="opportunity_window",
        category="seo",
        default_title="Duplicate title tags detected",
        default_description="Different pages share identical title tags.",
        what_issue_means="Multiple URLs share identical text inside their <title> tags.",
        why_it_matters="Identical title tags make it difficult to distinguish search listings and tab selections.",
        business_impact="Causes different products or offerings to compete with each other in search results.",
        seo_aeo_impact="Triggers search cannibalization as engines struggle to rank duplicate titles for unique pages.",
        default_impact_score=6.0,
        default_effort_score=3.0,
        default_urgency_score=5.0,
        default_confidence_score=8.8,
        business_relevance_score=6.0,
        exact_fix="Ensure every page has a distinct title that describes its unique content.",
        implementation_example="<title>Features - SwarmOps</title> vs <title>Pricing - SwarmOps</title>",
        verification_method="Scan your pages and verify no two unique pages share the same title text.",
        resolved_when="Every indexable URL contains a unique title tag.",
        evidence_safe_wording="Unique title tags clarify the topic of each individual page for search engines.",
        avoid_claims=["Duplicate titles cause manual action penalties", "Duplicate titles block crawling"],
        recommended_specialists=["seo", "content"]
    ),
    "missing_canonical": RegistryEntry(
        signal_type="opportunity_window",
        category="seo",
        default_title="Missing canonical URL tag",
        default_description="Canonical tags prevent duplicate content issues by specifying the preferred version.",
        what_issue_means="The HTML head does not contain a <link rel=\"canonical\"> tag.",
        why_it_matters="Canonical tags consolidate link equity and prevent duplicate URL structures (such as query parameters) from diluting rankings.",
        business_impact="Consolidates traffic data and link credentials to your primary canonical landing pages.",
        seo_aeo_impact="Instructs search engines to index only the primary URL, avoiding duplicate index clutter.",
        default_impact_score=5.0,
        default_effort_score=2.0,
        default_urgency_score=4.0,
        default_confidence_score=9.2,
        business_relevance_score=5.0,
        exact_fix="Add a self-referencing <link rel=\"canonical\" href=\"...\"> tag to the HTML head.",
        implementation_example="<link rel=\"canonical\" href=\"https://shravanpayyavula.me/\">",
        verification_method="Inspect the HTML head for a rel='canonical' link matching the page's canonical URL.",
        resolved_when="A canonical link tag is present and points to a valid absolute URL.",
        evidence_safe_wording="Canonical link tags specify the preferred indexable URL of the page.",
        avoid_claims=["Canonical tags stop other domains from scraping", "Canonical tags increase speed by 10%"],
        recommended_specialists=["seo", "operations"]
    ),
    "missing_json_ld": RegistryEntry(
        signal_type="opportunity_window",
        category="seo",
        default_title="No JSON-LD schema detected",
        default_description="Structured data helps search engines understand your content better.",
        what_issue_means="The page HTML contains no <script type=\"application/ld+json\"> schema blocks.",
        why_it_matters="Structured data gives search engines explicit clues about the meaning of a page and can support machine understanding.",
        business_impact="Enables your business listing to display rich results, stars, reviews, and detailed search visual cards.",
        seo_aeo_impact="Provides machines and LLMs with clear, semantic context to read your entity properties.",
        default_impact_score=6.0,
        default_effort_score=3.0,
        default_urgency_score=5.0,
        default_confidence_score=9.5,
        business_relevance_score=6.0,
        exact_fix="Implement a JSON-LD structured data block representing your page entity.",
        implementation_example="<script type=\"application/ld+json\">\n{\n  \"@context\": \"https://schema.org\",\n  \"@type\": \"WebSite\",\n  \"name\": \"SwarmOps\"\n}\n</script>",
        verification_method="Inspect the HTML source code for the presence of application/ld+json scripts.",
        resolved_when="A valid JSON-LD schema script is detected in the page source.",
        evidence_safe_wording="Structured data gives search engines explicit clues about the meaning of a page and can support machine understanding.",
        avoid_claims=["Schema is critical for ChatGPT/Perplexity/Gemini citation", "Schema increases rankings directly by 50%"],
        recommended_specialists=["aeo", "seo", "operations"]
    ),
    "missing_person_schema": RegistryEntry(
        signal_type="opportunity_window",
        category="content",
        default_title="Missing Person schema markup",
        default_description="Person schema details professional credentials and biographical entity details.",
        what_issue_means="No Person schema was declared on the profile, author, or about pages.",
        why_it_matters="Person schema supports Author E-E-A-T credentials, establishing biographical links for trust.",
        business_impact="Builds professional credibility for founders, authors, and executive leaders in search profiles.",
        seo_aeo_impact="Connects the author entity to their social profiles and organization entities in search knowledge graphs.",
        default_impact_score=5.0,
        default_effort_score=3.0,
        default_urgency_score=3.0,
        default_confidence_score=8.5,
        business_relevance_score=5.0,
        exact_fix="Embed a Person schema block on your about page detailing name, job title, and social links.",
        implementation_example="{\n  \"@context\": \"https://schema.org\",\n  \"@type\": \"Person\",\n  \"name\": \"Shravan Payyavula\",\n  \"url\": \"https://shravanpayyavula.me\"\n}",
        verification_method="Run schema validation on your about page to check for a valid Person entity.",
        resolved_when="A Person structured data block is successfully parsed from the about/homepage.",
        evidence_safe_wording="Person structured schema connects personal brand entities to search knowledge bases.",
        avoid_claims=["Person schema prevents negative PR", "Person schema guarantees a Google Knowledge Panel in 2 days"],
        recommended_specialists=["aeo", "seo", "content"]
    ),
    "missing_organization_schema": RegistryEntry(
        signal_type="opportunity_window",
        category="seo",
        default_title="Missing Organization schema markup",
        default_description="Organization schema defines corporate identity, logo, and contact info.",
        what_issue_means="No Organization or Brand schema was found on the homepage or contact page.",
        why_it_matters="Organization schema helps search engines populate Knowledge Panels and connect official brand assets.",
        business_impact="Ensures your corporate brand logo, customer support contacts, and social channels display correctly in Google Brand Cards.",
        seo_aeo_impact="Maps organization properties (founder, address, subsidiaries) to search knowledge graphs.",
        default_impact_score=6.0,
        default_effort_score=3.0,
        default_urgency_score=4.0,
        default_confidence_score=9.0,
        business_relevance_score=6.0,
        exact_fix="Configure an Organization JSON-LD script containing your logo, name, and social handles.",
        implementation_example="{\n  \"@context\": \"https://schema.org\",\n  \"@type\": \"Organization\",\n  \"name\": \"SwarmOps Inc\",\n  \"logo\": \"https://swarmops.com/logo.png\"\n}",
        verification_method="Verify that the homepage contains a script containing @type: Organization.",
        resolved_when="Organization schema is found and parses with zero critical syntax errors.",
        evidence_safe_wording="Organization schema defines business entity metadata for search engines.",
        avoid_claims=["Organization schema guarantees brand verification", "Organization schema blocks competitor listings"],
        recommended_specialists=["aeo", "seo", "operations"]
    ),
    "missing_open_graph": RegistryEntry(
        signal_type="opportunity_window",
        category="content",
        default_title="Missing Open Graph metadata tags",
        default_description="Open Graph tags optimize previews when links are shared on social platforms.",
        what_issue_means="The HTML head does not contain og:title, og:description, or og:image tags.",
        why_it_matters="Open Graph tags control how links look when shared on LinkedIn, Twitter, Slack, or Facebook.",
        business_impact="Improves click-through rates and branding appearance when team members or clients share your links.",
        seo_aeo_impact="Enforces consistent rich card snippet rendering on downstream communication channels.",
        default_impact_score=4.0,
        default_effort_score=2.0,
        default_urgency_score=3.0,
        default_confidence_score=9.0,
        business_relevance_score=4.0,
        exact_fix="Add standard meta property tags for og:title, og:description, og:url, and og:image.",
        implementation_example="<meta property=\"og:title\" content=\"SwarmOps | AI Marketing\">\n<meta property=\"og:image\" content=\"/og-card.png\">",
        verification_method="Inspect the HTML head for tags starting with meta property='og:...'.",
        resolved_when="At least og:title and og:image tags are detected in the page header.",
        evidence_safe_wording="Open Graph tags structure title, image, and description properties for social links.",
        avoid_claims=["Open Graph tags improve Google pagerank", "Open Graph tags are required for email deliverability"],
        recommended_specialists=["content", "cro"]
    ),
    "missing_ga4_or_gtm": RegistryEntry(
        signal_type="opportunity_window",
        category="analytics",
        default_title="Missing Google Analytics (GA4) or GTM tag",
        default_description="Analytics tags track user traffic, scroll depth, and goal events.",
        what_issue_means="The HTML does not contain Google Tag Manager or Google Analytics script signatures.",
        why_it_matters="Without analytics tracking, you cannot measure traffic volume, bounce rates, attribution, or conversion success.",
        business_impact="Leads to blind marketing spend because there is no loop returning conversion performance data.",
        seo_aeo_impact="Prevents attribution measurement and conversion signal capture on landing pages.",
        default_impact_score=8.0,
        default_effort_score=2.0,
        default_urgency_score=8.0,
        default_confidence_score=9.7,
        business_relevance_score=8.0,
        exact_fix="Install the GA4 tag or GTM script block inside your site head and body.",
        implementation_example="<script async src=\"https://www.googletagmanager.com/gtag/js?id=G-XXXXXXXXXX\"></script>",
        verification_method="Inspect the rendered HTML for a Google Tag Manager container ID or gtag script.",
        resolved_when="A valid GTM or GA4 tracking tag is successfully parsed from the DOM.",
        evidence_safe_wording="Analytics tags collect visitor metrics to measure marketing performance.",
        avoid_claims=["Analytics tags increase speed", "Installing Google Analytics instantly increases organic traffic by 10%"],
        recommended_specialists=["analytics", "cro", "operations"]
    ),
    "missing_primary_cta": RegistryEntry(
        signal_type="opportunity_window",
        category="cro",
        default_title="Missing clear primary Call to Action (CTA)",
        default_description="CTAs guide visitors toward the desired action (e.g. signup, contact).",
        what_issue_means="No prominent primary button or link is visible in the page header or hero section.",
        why_it_matters="Clear CTAs focus user attention, lower friction, and improve conversion rate metrics.",
        business_impact="Reduces landing page conversion rates by leaving visitors confused about the next step.",
        seo_aeo_impact="Negatively impacts session engagement metrics and user conversion flow paths.",
        default_impact_score=7.0,
        default_effort_score=2.0,
        default_urgency_score=7.0,
        default_confidence_score=8.0,
        business_relevance_score=7.0,
        exact_fix="Insert a prominent, high-contrast button (e.g., 'Get Started' or 'Book a Demo') in the hero viewport.",
        implementation_example="<a href=\"/signup\" class=\"bg-primary text-white px-6 py-3 font-semibold rounded-lg\">Get Started Free</a>",
        verification_method="Scan the page DOM for links or buttons located in the header/hero area.",
        resolved_when="At least one highly visible CTA link is identified in the top section.",
        evidence_safe_wording="Clear primary calls-to-action guide visitors toward conversion next steps.",
        avoid_claims=["Adding a CTA button increases revenue by 500% guaranteed", "CTA color has a psychological rank benefit"],
        recommended_specialists=["cro", "content", "paid_media"]
    ),
    "missing_lead_capture": RegistryEntry(
        signal_type="opportunity_window",
        category="cro",
        default_title="No lead capture form detected",
        default_description="Lead capture forms gather contact information from prospective leads.",
        what_issue_means="No email collection forms or inputs were detected on the page.",
        why_it_matters="A website without contact collection forms cannot capture passive traffic, lowering return on ad spend.",
        business_impact="Prevents email list building and downstream email lifecycle nurture campaigns.",
        seo_aeo_impact="Fails to convert organic traffic search clicks into structured pipeline prospects.",
        default_impact_score=7.0,
        default_effort_score=3.0,
        default_urgency_score=6.0,
        default_confidence_score=8.5,
        business_relevance_score=7.0,
        exact_fix="Embed a simple email sign-up input or contact form above the fold or in the footer.",
        implementation_example="<form><input type=\"email\" placeholder=\"Enter your email\"><button type=\"submit\">Subscribe</button></form>",
        verification_method="Audit form element markup to check for input fields with type='email' or 'text'.",
        resolved_when="A populated form element containing text/email inputs is parsed on the page.",
        evidence_safe_wording="Lead capture forms allow interested visitors to submit contact requests.",
        avoid_claims=["Contact forms guarantee 100% data compliance", "Lead capture forms double close rates"],
        recommended_specialists=["cro", "analytics", "operations"]
    ),
    "weak_trust_signals": RegistryEntry(
        signal_type="opportunity_window",
        category="cro",
        default_title="Weak trust signals detected",
        default_description="Trust signals include reviews, logos, and testimonials that build buyer confidence.",
        what_issue_means="The landing page lacks reviews, testimonials, security badges, or customer logos.",
        why_it_matters="Social proof and security signals address user anxiety, which helps increase conversion rates.",
        business_impact="High checkout or signup bounce rates because visitors feel uncertain about company legitimacy.",
        seo_aeo_impact="Engagement time may decrease if visitors do not immediately trust the page credentials.",
        default_impact_score=6.0,
        default_effort_score=4.0,
        default_urgency_score=5.0,
        default_confidence_score=8.0,
        business_relevance_score=6.0,
        exact_fix="Add a customer review quote section or client logos directly beneath the hero viewport.",
        implementation_example="<div class=\"testimonials\"><blockquote>SwarmOps automated our entire agency audit cycle.</blockquote> - Garry T.</div>",
        verification_method="Inspect the DOM for testimonial blocks, client logos, reviews, or secure SSL shields.",
        resolved_when="Social proof content (quotes, client logos, review cards) is detected on the page.",
        evidence_safe_wording="Testimonials and reviews help establish commercial trust for landing page visitors.",
        avoid_claims=["Testimonials instantly double domain trust scores", "Reviews guarantee protection from spam"],
        recommended_specialists=["cro", "content", "paid_media"]
    )
}
